### ISSUE TITLE
Fix project query against empty (no projects) commons - breaks portal

### ISSUE THREAD

**Issue by frickjack** [uc-cdis/peregrine#25]
```
{query: "query Test { project(first:10000) {code, project_id}}"}
```
against an empty commons results in 500 response:

```
ProgrammingError: (ProgrammingError) permission denied for relation node_project
 'SELECT node_project.created AS node_project_created, node_project.acl AS node_project_acl, node_project._sysan AS node_project__sysan, node_project._props AS node_project__props, node_project.node_id AS node_project_node_id \nFROM node_project \nWHERE node_project._props @> %(_props_1)s \n LIMIT %(param_1)s' {'_props_1': '{"dbgap_accession_number": "acct"}', 'param_1': 1}
[2018-02-07 22:28:46,038][peregrine.api][  ERROR] (ProgrammingError) permission denied for relation node_project
 'SELECT node_project.created AS node_project_created, node_project.acl AS node_project_acl, node_project._sysan AS node_project__sysan, node_project._props AS node_project__props, node_project.node_id AS node_project_node_id \nFROM node_project \nWHERE node_project._props @> %(_props_1)s \n LIMIT %(param_1)s' {'_props_1': '{"dbgap_accession_number": "acct"}', 'param_1': 1}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/peregrine/peregrine/auth/__init__.py", line 335, in f
    return func(*args, **kwargs)
  File "/peregrine/peregrine/resources/submission/__init__.py", line 77, in root_graphql_query
    set_read_access_projects()
  File "/peregrine/peregrine/resources/submission/__init__.py", line 62, in set_read_access_projects
    flask.g.read_access_projects = flask.g.user.get_project_ids('read')
  File "/peregrine/peregrine/auth/__init__.py", line 273, in get_project_ids
    self.project_ids[role] = self.fetch_project_ids(role)
  File "/peregrine/peregrine/auth/__init__.py", line 267, in fetch_project_ids
    result += self.get_projects_mapping(phsid)
  File "/peregrine/peregrine/auth/__init__.py", line 202, in get_projects_mapping
    dbgap_accession_number=phsid).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2370, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2231, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2441, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2456, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
```

**Comment by giangbui** [comment]
DB is not created !!!
======================================================
giangb@ip-172-24-66-152:~/devplanetv1_output$ g3k psql peregrine
psql (9.5.12, server 9.6.6)
WARNING: psql major version 9.5, server major version 9.6.
         Some psql features might not work.
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

============================================================

giangb@ip-172-24-66-152:~/devplanetv1_output$ psql -h devplanetv1-gdcapidb.cwvizkxhzjt8.us-east-1.rds.amazonaws.com -U peregrine
Password for user peregrine:
psql: FATAL:  database "peregrine" does not exist
giangb@ip-172-24-66-152:~/devplanetv1_output$
brain=> \dt
No relations found.
brain=>

**Comment by giangbui** [comment]
Spent 2 hours so far.

**Comment by philloooo** [comment]
it's because the database is empty, no bug here
